default_scrape_interval: 10s

data_dir: /tmp/vmscraper_data

export_endpoint: "http://localhost:8428/api/v1/import"
export_interval: 1s
export_batch_size: 2048

scratch_buffer_size: 1048576

targets:
  - endpoint: "http://localhost:9100/metrics"
    output_buffer_size: 262144

  - endpoint: "http://vh.rischmann.fr:9100/metrics"
    output_buffer_size: 262144
